from privacy import PV, HIDDEN
# 정밀조립존 OCS Cell 추천 제품·제조사·단가 + 출처 + 수량 근거 + SW Use Case
# P 값은 만원 단위로 보관하고 화면에는 천원으로 표시. 근거 문구 속 원화 금액은 천원 단위.
# 환율 가정: USD 1,400원 · EUR 1,550원 · GBP 1,800원 · AUD 900원 · CAD 1,000원 · HKD 180원
# 가격 근거 등급 (2026-10-07 재확인):
#   [공개가·확인] 링크 페이지를 직접 열어 가격·사양을 확인
#   [공개가·검색] 판매처가 자동 접속을 막아 검색 결과 요약으로만 확인 (브라우저에서 재확인 필요)
#   [견적] 내부 견적·정가표   /   [추정] 공개 가격 없음 → 견적 필요

FX = "USD 1,400원 · EUR 1,550원 · GBP 1,800원 · AUD 900원 · CAD 1,000원 · HKD 180원"

P = {
    # ---------------- HW
    "LS":   ("CoreRidge KR587S4 (2U 2소켓 Intel Xeon 6 P-core) + 25GbE×2 OCP 3.0 NIC", "KTNF (한국)", 2800, "[추정] 공개가·조달 쇼핑몰 가격 확인되지 않음 → 견적 필요. 사양은 KTNF 공식 사양 페이지로 확인(Xeon 6 P-core 2소켓, DDR5 32슬롯 최대 8TB, PCIe Gen5, OCP 3.0). 온보드 LAN이 없어 25GbE NIC 별도"),
    "GPU":  ("AS-4125GS-TNRT (4U, GPU 8장 지원) + RTX PRO 6000 Blackwell Max-Q 96GB × 4", "Supermicro (미국) · NVIDIA", 13840,
             "[공개가·확인+견적] 섀시 시작가 €16,242 ≈ 25,200 + 메모리·NVMe 약 10,500 + GPU 4장 102,700(내부 견적 25,670/장). Max-Q 지원은 Supermicro 사양 페이지에서 확인"),
    "STO":  ("CoreRidge KR587S4 12베이 + 20TB HDD × 12 (raw 240TB) + NVMe 캐시 · Ceph SDS", "KTNF (한국) + Ceph (오픈소스)", 2900, "[추정] 서버 약 20,000 + 20TB 엔터프라이즈 HDD 12개 약 7,200 + NVMe 캐시 약 1,800. 12베이 구성은 KTNF 사양 페이지로 확인. Ceph 라이선스 무료"),
    "BAK":  ("RackStation RS2423RP+ + 12TB HDD × 8", "Synology (대만)", 800, "[공개가·확인] €4,013(VAT 25.5% 포함) → VAT 제외 약 €3,198 ≈ 4,960 + HDD 8개 약 3,000"),
    "EGW":  ("Nuvo-10208GC + RTX 2000 Ada · 64GB · 10GBASE-T 옵션 · NVMe 4TB", "Neousys (대만)", 820, "[공개가·검색] 본체 시작가 $3,060 ≈ 4,280 + GPU·메모리·10G·NVMe 약 3,900. 영상 버퍼는 영상 수집 노드가 맡아 HDD 제외. 사양(최대 64GB, 10GBASE-T 옵션)은 확인"),
    "VNODE": ("SYS-E403-14B-FRN2T (Xeon 6 · 128GB) + NVIDIA L4 24GB + U.2 NVMe 3.84TB×2 + 24TB HDD×2", "Supermicro (미국) · NVIDIA", 1720,
              "[공개가·확인] 본체 $5,187 ≈ 7,260 / [공개가·검색] L4 $3,000~3,995 ≈ 4,200~5,590 → 4,800 + 메모리 128GB 약 1,500 · NVMe 2개 약 2,200 · HDD 2개 약 1,400 [추정]"),
    "CAB":  ("18U 월마운트 캐비닛 + Smart-UPS SMT2200RMI2UC (2.2kVA)", "국산 랙 + APC (Schneider, 프랑스)", 520, "[추정] EGW·영상 수집 노드·셀 스위치 부하 약 1.2kW를 받도록 UPS를 1kVA → 2.2kVA로 상향. 캐비닛·광패치 약 2,560 포함"),
    "CORE": ("Nexus 93180YC-FX3 (48×25G + 6×100G) + 광 모듈", "Cisco (미국)", 1850,
             "[공개가·확인] HK$74,168 ≈ 13,350 / [공개가·검색] SHI $18,100 ≈ 25,340, 지자체 RFQ $9,993~11,071. 약 $11,000 ≈ 15,400 + SFP28·QSFP 광 모듈 약 3,100"),
    "TSN":  ("TSN-G5008-2GTXSFP (6×GbE + 2×콤보, 802.1AS·Qbv)", "Moxa (대만)", 350, "[추정] 공개가 없음. 포트 구성·TSN 규격은 Moxa 페이지에서 확인"),
    "POE":  ("Catalyst C9300-24UX-E (24×mGig UPOE) + C9300-NM-8X 업링크 모듈", "Cisco (미국)", 1300,
             "[공개가·검색] €7,193(VAT 제외) ≈ 11,150, $7,870 ≈ 11,020 + 업링크 모듈 약 2,000 [추정]"),
    "MGT":  ("Catalyst 1300-48T-4G (48×1G)", "Cisco (미국)", 170, "[공개가·확인] HK$9,708 ≈ 1,750"),
    "FW":   ("BLUEMAX NGF (HA 쌍 구성)", "시큐아이 (한국)", 2200, "[추정] 공개가 없음. OPC UA·MQTT DPI 지원 여부 확인 필요"),
    "PTP":  ("microSyncHR (GNSS · IEEE 1588 / 802.1AS 프로파일)", "Meinberg (독일)", 1700, "[추정] 공개가 없음. 802.1AS 프로파일 지원은 제조사 자료로 확인"),
    "AP":   ("Catalyst IW9167EH-x-AP (Wi-Fi 6E, 국내 규제 도메인) + 외장 안테나", "Cisco (미국)", 500,
             "[공개가·확인] IW9167EH-B-AP $2,873 ≈ 4,020 + 안테나 약 1,000 [추정]"),
    "FIB":  ("광 트렁크(OM4)·Cat6A·케이블 트레이 시공", "국내 정보통신 공사업체", 5900, "[추정] 셀 5개 구간 + 서버실 라이저"),
    "OWS":  ("Pro Max Tower T2 (Core Ultra 9 285K · 64GB) + 32″ 4K × 2", "Dell (미국)", 460,
             "[공개가·확인] 기본 £1,248(VAT 제외) + Ultra 9 285K £438 ≈ 3,030 + 메모리 약 600 + 모니터 2대 약 1,000 [추정]"),
    "DWS":  ("Precision 7960 Tower (Xeon w7-3555 · RTX PRO 6000 96GB) + 256GB 메모리", "Dell (미국)", 3950,
             "[공개가·확인] $24,635(32GB 구성) ≈ 34,490 + 메모리 증설 약 5,000 [추정]"),
    "VW":   ("VM55B-U 55″ × 4 + 비디오월 컨트롤러·브래킷", "삼성전자 (한국)", 1420,
             "[공개가·확인] 대당 CAD 2,042 ≈ 2,040 × 4 + 컨트롤러·브래킷 약 6,000 [추정]"),
    "RACK": ("42U 서버랙 (1,200mm) + 이중 PDU", "국산 랙 제조사", 280, "[추정]"),
    "UPS":  ("Eaton 9E 20kVA (9E20KI) + 확장 배터리(30분)", "Eaton (미국·아일랜드)", 1500,
             "[공개가·확인] AUD 12,790(GST 포함) → GST 제외 ≈ 10,460, 기본 10분 + 확장 배터리 약 4,500 [추정]"),
    "CRAC": ("Liebert CRV CR020RA (인로우, 20kW)", "Vertiv (미국)", 2800, "[추정] 공개가 없음. 용량 20kW는 제조사 페이지(검색 요약)로 확인"),
    "KVM":  ("KN1108VA IP-KVM + 랙 콘솔", "ATEN (대만)", 350, "[공개가·확인] $1,525 ≈ 2,140 + 콘솔 약 1,300 [추정]"),
    # ---------------- SW
    "OPCUA": ("KEPServerEX (OPC UA Server · IoT Gateway)", "PTC Kepware (미국)", 1500, "[추정] 드라이버 조합별 견적"),
    "AASIM": ("AAS 서브모델·OPC UA 정보모델 정의 (OPC 30270 기반)", "캠틱 정의 + AAS 전문기관 자문", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). 서브모델·Semantic ID 정의는 캠틱 수행(외부 자문은 별도 협의)"),
    "DRV":   ("Kepware 드라이버 + 로봇 SDK·ROS2 브리지 개발", "PTC Kepware + 자체 개발", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). Kepware 드라이버는 KEPServerEX 라이선스에 포함, 로봇 SDK·ROS 2 연동은 연구 인력 수행"),
    "ETSDB": ("InfluxDB 3 Core", "InfluxData (미국, 오픈소스)", 0, "무료"),
    "RAW":   ("원시데이터 청크 업로드·store-and-forward 모듈", "자체 개발 (위탁)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "GWM":   ("K3s + Rancher (오픈소스)", "SUSE (독일)", 0, "무료 · Prime 구독은 선택"),
    "EAI":   ("TensorRT · ONNX Runtime · DXNN SDK", "NVIDIA · Microsoft · 딥엑스", 0, "무료"),
    "K8S":   ("RKE2 (K8s HA 3노드) + Rancher 관리", "SUSE (독일, 오픈소스 Apache 2.0)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). 엣지 K3s·Rancher와 같은 계열로 관리 체계 통일. 국산 상용(Cocktail Cloud, 약 30,000 [추정])은 제외"),
    "AASR":  ("Eclipse BaSyx (AAS Repository·Registry, AAS V3)", "Eclipse Foundation (오픈소스, MIT)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "OTSDB": ("Machbase Cluster Edition (Neo 인터페이스, HA)", "마크베이스 (한국)", 4500, "[추정] 공개가 없음. HA는 Cluster Edition에서 지원(Neo 단일 노드는 HA 미지원)"),
    "LAKE":  ("Apache Iceberg + Nessie 카탈로그 구축", "Apache·Project Nessie (오픈소스)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "FS":    ("Feast Feature Store 구축", "Feast (오픈소스)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "INF":   ("Triton Inference Server (오픈소스, BSD)", "NVIDIA (오픈소스)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). NVIDIA AI Enterprise 구독($4,500/GPU/년)은 기술 지원·장기 지원 버전용이라 제외, 상용 운영 전환 시 재검토"),
    "ETL":   ("Apache Airflow 기반 AI Ready 변환 파이프라인", "Apache (오픈소스) + 자체 개발", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "MQTT":  ("RabbitMQ 3노드 클러스터 (MQTT 5 플러그인·quorum 큐) + REST 게이트웨이 자체 구현", "Broadcom (미국, 오픈소스 MPL 2.0) + 자체 개발", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). HiveMQ Enterprise(유료 클러스터)는 제외, EMQX는 중국 기업이라 제외. 브로커 장애 시에도 데이터는 로컬 Data Lake에 남아 재전송 가능"),
    "CAT":   ("OpenMetadata 구축", "OpenMetadata (오픈소스)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "OCS":   ("존 오케스트레이터 (Manufacturing·Field Logistics Agent)", "자체 개발 (총괄1 PA Agent 연계)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "DMW":   ("DMWorks 3.0 BASE + MULTIPLE PROCESS + PLC SIMULATION", "이지로보틱스 (한국)", PV.DMW_PZ if PV else 0, PV.DMW_PZ_NOTE if PV else HIDDEN),
    "ISAAC": ("Isaac Sim · Isaac Lab", "NVIDIA", 0, "무료"),
    "MON":   ("Prometheus + Grafana + Loki 구축", "오픈소스", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
    "SEC":   ("Keycloak + HIWARE 접근통제 + OPC UA 인증서 PKI", "오픈소스 + 넷앤드 (한국)", 3500, "[추정] HIWARE 공개가 없음"),
    "TRC":   ("검증 연계 Trace API", "자체 개발 (TTA 협의)", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리)"),
}

SRC = {
    "LS": [("KTNF 공식 사양(KR587S4)", "https://www.ktnf.co.kr/kor/product/spec.php?idx=83&pNo=1&p1=2&p2=9"),
           ("KTNF x86 서버 목록", "https://www.ktnf.co.kr/kor/product/list.php?p1=2")],
    "GPU": [("섀시 사양(Max-Q 지원)", "https://www.supermicro.com/ja/products/system/gpu/4u/as-4125gs-tnrt"),
            ("섀시 가격", "https://store.supermicro.com/nl_de/as-4125gs-tnrt.html"),
            ("GPU 사양", "https://www.pugetsystems.com/parts/Video-Card/NVIDIA-RTX-PRO-6000-Blackwell-Max-Q-Workstation-Edition-96GB-PCI-E-16222/"),
            ("GPU 가격 동향", "https://www.tomshardware.com/pc-components/gpus/nvidia-raises-rtx-pro-6000-blackwell-gpu-pricing-to-usd13-250-55-percent-increase-over-msrp-in-a-years-time")],
    "STO": [("KTNF 공식 사양(KR587S4)", "https://www.ktnf.co.kr/kor/product/spec.php?idx=83&pNo=1&p1=2&p2=9"), ("Ceph", "https://ceph.io/en/")],
    "BAK": [("사양", "https://mariushosting.com/synology-rackstation-rs2423-release-date-and-specs/"),
            ("가격", "https://multitronic.fi/en/products/4389925/synology-rackstation--12-bay--amd-quad-core--8gb-ram--synology-hdd-ssd")],
    "EGW": [("사양", "https://www.bvm.co.uk/products/neousys-nuvo-10208gc-intel-alder-lake-raptor-lake-edge-ai-platform-supporting-dual-350w-nvidia-rtx-gpu/"),
            ("가격(검색)", "https://coastipc.com/nuvo-10208gc-industrial-grade-edge-ai-platform-supporting-dual-nvidia-rtx-series-350w-gpu-cards-intel-14th-13th-12th-gen-core-processors-3x-additional-pcie-slots-10g-2-5g-1g-ethernet")],
    "VNODE": [("본체 사양·가격", "https://store.supermicro.com/us_en/iot-embedded-sys-e403-14b-frn2t.html"),
              ("L4 사양", "https://www.nvidia.com/en-us/data-center/l4/"),
              ("L4 가격(검색)", "https://www.centralcomputer.com/nvidia-900-2g193-0000-000-tesla-l4-24gb-graphics-card-75w.html")],
    "CAB": [],
    "CORE": [("사양·가격", "https://network-switch.com/products/network-switch-cisco-data-center-switches-nexus9300-93180yc-48xsfp28-25g-6xqsfp28-ports-100g-ethernet"),
             ("가격(검색)", "https://www.shi.com/product/42112975/Cisco-Nexus-93180YC-FX3")],
    "TSN": [("제품·데이터시트", "https://www.moxa.com/en/products/industrial-network-infrastructure/ethernet-switches/layer-2-managed-switches/tsn-g5008-series")],
    "POE": [("가격(검색)", "https://servermall.com/catalog/hardware/cisco-catalyst-c9300-24ux-e/"),
            ("가격(검색)", "https://directmacro.com/cisco-c9300-24ux-e-network-switch.html")],
    "MGT": [("사양·가격", "https://network-switch.com/products/cisco-c1300-48t-4g")],
    "FW": [("제품 소개", "https://www.boannews.com/html/detail.html?idx=139907")],
    "PTP": [("제품", "https://www.meinbergglobal.com/english/archive/microsync-hr.htm"),
            ("제품(미국)", "https://www.meinberg-usa.com/products/microsync-series/microSync-hr.htm")],
    "AP": [("가격", "https://www.hummingbirdnetworks.com/cisco-systems-iw9167-wi-fi-6e-access-point-with-8-rf-ports-b-domain-and-wi-fi-mode-support-iw9167eh-b-ap"),
           ("데이터시트", "https://www.cisco.com/c/en/us/products/collateral/wireless/catalyst-iw9167-series/cat-iw9167e-heavy-duty-ap-ds.html")],
    "FIB": [],
    "OWS": [("제품·가격", "https://www.dell.com/en-uk/shop/cty/pdp/spd/dell-pro-max-fct2250-desktop")],
    "DWS": [("제품", "https://www.dell.com/en-my/shop/cty/pdp/spd/precision-t7960-workstation"),
            ("가격", "https://www.monitors.com/products/dell-7960-xeon-w7-3555-32gb-rtx-pro-6000-blackwell")],
    "VW": [("사양", "https://www.samsung.com/ph/smart-signage/video-wall/vmb-u-55-inch-fhd-1080p-500nit-ip5x-3-5mm-lh55vmbubgbxxp"),
           ("가격", "https://deploydepot.ca/products/samsung-vm55b-u-digital-signage-display-lh55vmbubgbxgo")],
    "RACK": [],
    "UPS": [("제품·가격", "https://store.area9.com.au/products/eaton-9e-20kva-16kw-online-tower-ups-hw-1270318")],
    "CRAC": [("제품", "https://www.vertiv.com/en-us/products-catalog/thermal-management/in-row-cooling/cr020ra-air-cooled-20kw"),
             ("데이터시트", "https://www.vertiv.com/49e99c/globalassets/products/thermal-management/in-row-cooling/vertiv-liebert-crv-data-sheet-sl-11998.pdf")],
    "KVM": [("제품", "https://www.aten.com/eu/en/products/kvm/kvm-over-ip-switches/kn1108va/"),
            ("가격", "https://esaitech.com/products/aten-kn1108va-kvm-over-ip-switch-taa-compliant-8-computers-1-local-users-1-remote-users-1920-x-1200-14-x-network-rj-45-2-x-ps-2-port-6-x-usb1-x-vga-desktop-rack-mountable-1u")],
    "OPCUA": [("제품", "https://www.ptc.com/en/products/kepware/kepserverex")],
    "AASIM": [("OPC 30270 규격", "https://reference.opcfoundation.org/specs/OPC-30270/3.3"),
              ("I4AAS", "https://opcfoundation.org/markets-collaboration/i4aas/")],
    "DRV": [("Kepware", "https://www.ptc.com/en/products/kepware/kepserverex")],
    "ETSDB": [("문서", "https://docs.influxdata.com/influxdb3/core/")],
    "RAW": [],
    "GWM": [("K3s", "https://k3s.io/")],
    "EAI": [("TensorRT", "https://developer.nvidia.com/tensorrt"), ("ONNX Runtime", "https://onnxruntime.ai/"), ("딥엑스", "https://deepx.ai/")],
    "K8S": [("RKE2", "https://docs.rke2.io/"), ("Rancher", "https://www.rancher.com/")],
    "AASR": [("BaSyx (GitHub)", "https://github.com/eclipse-basyx/basyx-java-server-sdk")],
    "OTSDB": [("문서(Cluster Edition)", "https://docs.machbase.com/neo/"), ("제품 개요", "https://db-engines.com/en/system/Machbase+Neo")],
    "LAKE": [("Iceberg", "https://iceberg.apache.org/"), ("Nessie", "https://projectnessie.org/")],
    "FS": [("Feast", "https://feast.dev/")],
    "INF": [("Triton", "https://developer.nvidia.com/triton-inference-server"),
            ("Triton (GitHub, BSD)", "https://github.com/triton-inference-server/server")],
    "ETL": [("Airflow", "https://airflow.apache.org/")],
    "MQTT": [("RabbitMQ MQTT 플러그인", "https://www.rabbitmq.com/docs/mqtt"), ("RabbitMQ 클러스터링", "https://www.rabbitmq.com/docs/clustering")],
    "CAT": [("OpenMetadata", "https://open-metadata.org/")],
    "OCS": [], "DMW": [],
    "ISAAC": [("Isaac Sim", "https://developer.nvidia.com/isaac/sim")],
    "MON": [("Prometheus", "https://prometheus.io/"), ("Grafana", "https://grafana.com/oss/grafana/")],
    "SEC": [("Keycloak", "https://www.keycloak.org/"), ("HIWARE", "https://m.boannews.com/html/detail.html?idx=144852")],
    "TRC": [],
}

BASIS = {
    "LS": "Kubernetes HA 최소 3노드(etcd 쿼럼). AAS Repository·TSDB·OCS를 노드 1대 장애에도 유지",
    "GPU": "추론(Triton) 1대 + 영상 비식별·합성데이터·재학습 1대. 실시간 추론과 배치 작업이 GPU를 다투지 않게 분리",
    "STO": "필요 1,026TB(존 월 263TB × 3개월 × 1.3) ÷ Ceph 권장 사용률 80% = usable 1,282TB ÷ 노드당 usable 160TB(raw 240TB × 이레이저 코딩 4+2) = 8.0 → 9대",
    "BAK": "AAS·TSDB·설정·모델만 백업(원시데이터 원본은 중앙 Golden Copy) → 50TB급 1대",
    "EGW": "셀 5개에 1대씩 + 존 예비 1대(냉예비). OPC UA 수집·AAS 매핑·시계열 버퍼·제어만 맡음(태그 약 9,450개/셀). 영상은 영상 수집 노드로 분리",
    "VNODE": "셀당 1대 × 5. 셀 카메라 45대 영상(고정 카메라 20대 직접 수신 + 로봇 엣지가 보내는 25대분) 평균 651Mbps를 받아 NVMe에 수신 → HDD 24TB(RAID1)에 7일분(약 16.7TB) 보관 → Data Lake로 업로드. L4 디코더 4개로 영상 AI(작업자 접근 감지 등) 처리. 10GbE 2포트를 셀 액세스 스위치 2대에 1회선씩 연결",
    "CAB": "셀당 1개 (EGW·영상 수집 노드·셀 스위치·UPS 수납)",
    "CORE": "MLAG 이중화 2대. 소요 포트 약 71개(로컬 서버 6, GPU 4, 스토리지 36[9노드×공용망·클러스터망], 셀 액세스 업링크 20, 백업·방화벽·관제·관리 5)를 2대에 나누면 대당 약 36포트 ≤ 48",
    "TSN": "셀별 TSN 연결 대상 = 협동로봇 컨트롤러 10 + 로봇 엣지 10 + PLC·안전PLC 2 + EGW 1 = 23포트(AMR·AMMR은 무선). 스위치당 가용 7포트 → 셀당 4대 × 5 = 20대",
    "POE": "로봇 카메라 45대(손목 D405·머리/가슴 D455)는 모두 USB3로 로봇 엣지에 직결해 PoE 포트를 쓰지 않음. 셀별 연결 대상 = 영상 수집 노드 2 + 공정설비·공정 비전·제어 PC·HMI 7~16 + AP 1 = 10~19포트. 대당 가용 22포트 → 셀당 1대 × 5 = 5대",
    "MGT": "서버·스토리지·스위치·UPS IPMI/관리 포트 약 20개 → 48포트 1대",
    "FW": "중앙 Server·TTA 연계 단일 경계를 HA 쌍으로 구성",
    "PTP": "존 단일 그랜드마스터. TSN·코어 스위치가 경계/투명 클럭으로 셀에 분배하고, GNSS 장애 시 홀드오버로 유지",
    "AP": "셀 내부 이동 로봇 5대(AMR 4·AMMR 1)가 셀당 약 350Mbps를 무선으로 올리므로 셀마다 1대 + 통로 2대 = 7대",
    "FIB": "셀 액세스 스위치 7대 × 10G 이중 광 + 카메라·AP 배선. 존 1식",
    "OWS": "존 관제 1인 + 셀 알람 대응 1인 동시 운영",
    "DWS": "DMWorks 검증 DT 1대 + Isaac 학습 DT 1대 (라이선스·GPU 분리)",
    "VW": "관제실 1식(55″ 2×2)",
    "RACK": "Rack A(연산: 로컬 서버 3·GPU 서버 2 = 14U) + Rack B(코어·방화벽·관리·백업·PTP) + Rack C(스토리지 9노드 18U·UPS 배터리)",
    "UPS": "서버실 부하 산정 약 12kW(서버 2.4 + GPU 서버 4.0 + 스토리지 9노드 4.5 + 네트워크·기타 1.3) → 20kVA(16kW) 1대, 30분 유지",
    "CRAC": "서버실 열부하 약 12kW → 20kW급 1대(여유 포함)",
    "KVM": "서버실 현장 유지보수용 1식",
    "OPCUA": "운용 EGW 5대에 1카피씩(예비 EGW는 고장 시 라이선스 이전)",
    "AASIM": "존 공통 정보모델 1식(셀별 인스턴스로 재사용)",
    "DRV": "로봇 기종군별 개발 3식 (A-3-5 / A-3-2·A-3-3 / A-3-1·A-3-4)",
    "ETSDB": "EGW 6대 설치(무료)",
    "RAW": "존 공통 모듈 1식, EGW 6대에 배포",
    "GWM": "존 공통 관리 1식",
    "EAI": "EGW 6대 설치(무료)",
    "K8S": "로컬 서버 클러스터 1식",
    "AASR": "존 1식", "OTSDB": "존 1식(3노드 클러스터)", "LAKE": "존 1식", "FS": "존 1식",
    "INF": "추론 GPU 서버(GPU-1) 1식",
    "ETL": "존 1식", "MQTT": "중앙 전송용 존 1식(3노드)", "CAT": "존 1식", "OCS": "존 1식",
    "DMW": "검증 DT 워크스테이션 1대용 1카피", "ISAAC": "학습 DT 워크스테이션용(무료)", "MON": "존 1식",
    "SEC": "존 1식", "TRC": "존 1식",
}

USE = {
    "OPCUA": "A-3-5 ST3에서 R4가 스크류를 체결하면 너트러너 토크·각도, PLC STEP 번호, 로봇 TCP 위치를 드라이버별로 읽어 OPC UA 주소공간 하나로 묶음 → AAS 'OperationalData' 태그로 매핑해 20ms 주기로 TSDB에 적재",
    "AASIM": "체결 유닛·디스펜서·로봇마다 Nameplate·TechnicalData·OperationalData·Maintenance 서브모델을 정의함. 2차년도 A-3-2에 같은 계열 서보 프레스가 들어와도 같은 Semantic ID를 써서 대시보드·AI 모델을 고치지 않고 재사용",
    "DRV": "기종이 다른 협동로봇의 관절각·토크·TCP·알람을 각 SDK로 읽어 공통 태그로 변환함. ROS2 브리지는 VLA 추론 노드가 쓰는 /joint_states·/wrench 토픽을 같은 타임스탬프로 기록",
    "ETSDB": "셀–서버실 회선이 끊기거나 Local Server를 점검하는 동안 EGW가 최대 7일치 시계열을 보관했다가 복구 후 자동 재전송 → 에피소드 데이터 누락 방지",
    "RAW": "영상 수집 노드가 셀 카메라 45대 영상(고정 카메라 RTSP 수신 + 로봇 엣지 업로드)을 받아 7일 버퍼에 쌓고, 청크 단위로 Data Lake(S3)에 올림. 실패한 청크는 체크섬으로 찾아 재전송",
    "GWM": "EGW 6대의 수집기·엣지 AI 모델 컨테이너 버전을 서버실에서 일괄 배포·롤백함. 신규 셀(A-3-1 등) 추가 시 설정 템플릿을 복제해 수집을 바로 시작",
    "EAI": "영상 수집 노드(L4)에서 작업자 접근 감지, EGW에서 F/T 이상 파형 감지 모델을 TensorRT로 실행해 100ms 안에 알람을 냄. 같은 모델을 딥엑스 NPU로 돌려 GPU 대비 지연·전력 비교 데이터를 만듦(NPU 실증존 연계)",
    "K8S": "AAS Repository·TSDB·Feature Store·Triton·OCS 등 로컬 서비스 약 20개를 3노드에 분산 배치함. 노드 1대가 고장 나면 자동 재배치로 존 운영이 멈추지 않음",
    "AASR": "존 안 모든 자산(로봇·공정설비·카메라)의 AAS를 등록·조회하는 기준 저장소. DT·DCC·중앙 Enterprise AAS가 같은 AAS ID로 장비를 찾음",
    "OTSDB": "셀 상태·알람·공정값(초당 약 20만 포인트)을 12개월 저장함. '지난주 A-3-5 체결 NG 때 토크 곡선' 같은 조회에 초 단위로 응답하고 DCC 대시보드의 원천 데이터가 됨",
    "LAKE": "원시 영상·파형·에피소드를 셀/일자/order ID로 나눠 버전 관리함. 학습팀이 '9월 도어트림 LH 100개 배치'를 스냅샷으로 고정해 같은 데이터로 재학습·재현",
    "FS": "체결 토크 이동평균, 최근 10회 NG율 같은 피처를 학습과 실시간 추론이 같은 정의로 씀 → 학습-운영 데이터 불일치 방지",
    "INF": "셀 상태머신이 HOLD·재시도·격리 중 무엇을 할지 판단하는 이상 판단 모델과 결합 OK/NG 판정 모델을 GPU 서버에서 서비스함(이상 판단 10초 KPI 대응)",
    "ETL": "배치가 끝나면 원시데이터를 시간 동기 정렬 → 결측·이상치 검사 → AAS 매핑 → LeRobot 포맷 변환 → 품질 리포트 생성 → 중앙 Manufacturing Data Lake로 전송",
    "MQTT": "AI Ready 데이터셋 메타데이터와 셀 KPI(사이클타임·NG율) 이벤트를 Sparkplug B로 중앙 Server·DCC에 발행하고, 중앙의 작업지시·모델 배포 메시지를 구독",
    "CAT": "데이터셋마다 출처 셀·수집 조건·버전·사용 모델을 기록해 '이 VLA 모델은 어떤 에피소드로 학습했나'를 역추적",
    "OCS": "공장 PA Agent가 내린 'LH 도어트림 100개' 오더를 셀1(체결)·셀2(압입)에 배정함. A-3-5 ST3가 멈추면 HOLD 후 재배정하고 납기 진척을 다시 예측",
    "DMW": "새 기종 지그를 넣기 전에 로봇 경로 간섭·사이클타임을 가상 시운전하고, PLC 프로그램을 가상 설비에 연결해 시퀀스 오류를 미리 찾음",
    "ISAAC": "VLA·파지 스킬 학습 씬과 합성 데이터를 만들고, 실물 에피소드를 리플레이해 S2R/R2S 정합 오차를 측정",
    "MON": "EGW·서버·스토리지·파이프라인 지표를 모아 디스크 사용률 80%, 수집 지연 5초 초과 시 알람",
    "SEC": "운영자·연구자 계정을 SSO로 통합하고 역할별 데이터 접근을 제한함. OPC UA 장비 인증서를 발급·폐기하고 서버 접속 기록을 감사 로그로 보관",
    "TRC": "OCS 명령 → PLC STEP 전이 → 로봇 동작 이벤트를 시간순 Trace로 남겨, TTA가 Expected Trace와 비교하는 상호운용성 검증에 제공",
}


# =====================================================================
# 셀 HW·SW — 로봇별 온디바이스 엣지 (셀당 협동로봇 10 + AMMR 1 = Thor급 11, AMR 4 = Orin급 4)
# 수량은 셀당, 금액은 5셀 합계로 표시. P 값은 만원 단위 보관(화면 천원 표시)
# =====================================================================
# (구분, 기호, 품목, 주요 스펙, 셀당 수량, 단위, 기능, 용도, 셀 BOM 계상 여부)
CELL_HW = [
    ("엣지 컴퓨터", "EDGE-T", "협동로봇·AMMR용 온디바이스 엣지", "Jetson AGX Thor(T5000) · 2,070 FP4 TFLOPS · Blackwell 2,560코어 GPU · Arm 14코어 · 128GB LPDDR5X · NVMe 1TB · 25GbE · 40~130W",
     11, "대", "VLA·파지·삽입 스킬 추론, 카메라 3대(손목 D405·머리/가슴 D455, USB3) 수신·기록, 로봇 제어 브리지, 안전·이상 감지", "협동로봇 10대 + AMMR 1대에 1대씩", "셀 BOM 'EDGE' 항목"),
    ("엣지 컴퓨터", "EDGE-O", "AMR용 온디바이스 엣지", "Jetson AGX Orin 64GB · 275 TOPS · Arm 12코어 · GbE 4포트(PoE 옵션) · 9~36VDC · 팬리스 · -10~60℃",
     4, "대", "LiDAR·카메라 인지, 도킹 정렬, 카메라 3대 기록, 무선 단절 시 로컬 버퍼·재전송", "AMR 4대에 1대씩", "셀 BOM 'EDGE' 항목"),
    ("엣지 부속", "SSD", "AMR 엣지용 NVMe SSD 2TB", "M.2 2280 NVMe · 산업용 · 2TB", 4, "개", "에피소드·영상 로컬 버퍼(약 100시간분)", "AMR 엣지 기본 SSD(64GB) 보완", "셀 BOM 'EDGE-K' 항목"),
    ("엣지 부속", "WLAN", "이동 로봇 무선 클라이언트", "산업용 Wi-Fi 6E 클라이언트 · 외장 안테나 · 로밍 지원", 5, "개", "AMR·AMMR 영상·텔레메트리 무선 업로드", "AMR 4 + AMMR 1", "셀 BOM 'EDGE-K' 항목"),
    ("엣지 부속", "5GM", "이동 로봇 5G 모뎀", "5G NR Sub-6 · n79(이음5G 4.7GHz) 포함 · 4G 폴백 · GbE로 온디바이스 엣지 연결 · 차량용 DC 입력 · 외장 5G 안테나", 5, "대",
     "이음5G 망으로 영상·텔레메트리 업로드, Wi-Fi 음영·로밍 구간과 셀 간 이동 중 연결 유지", "AMR 4 + AMMR 1 (5G 기지국·코어는 이음5G 별도, 본 목록 제외)", "셀 BOM 미포함(추가)"),
    ("엣지 부속", "KIT", "엣지 장착·전원 키트", "24VDC 절연 컨버터 · 방진 브래킷 · M12 산업용 Ethernet·USB3 케이블", 15, "식", "로봇 본체·베이스 장착, 전원·신호 연결", "엣지 15대", "셀 BOM 'EDGE-K' 항목"),
    ("NPU", "NPU-M", "국산 NPU 가속 모듈 (선택)", "DEEPX DX-M1 · M.2 · 엣지 NPU", 2, "개", "같은 모델을 GPU·NPU에서 돌려 지연·전력 비교", "NPU 실증존 연계 시험", "셀 BOM 미포함(추가)"),
]

# (구분, 기호, 품목, 주요 스펙, 수량, 단위, 기능, 용도·Use Case, 설치 노드(c:기호), 셀 BOM 계상 여부)
CELL_SW = [
    ("플랫폼", "JP", "JetPack (Jetson Linux · CUDA · TensorRT · cuDNN)", "Thor용 JetPack 7 · Orin용 JetPack 6", 75, "대", "엣지 OS·GPU 가속 라이브러리", "엣지 75대 기본 소프트웨어", "EDGE-T", "무료"),
    ("플랫폼", "ROS", "ROS 2 Jazzy + Isaac ROS", "ROS 2 LTS · Isaac ROS 인지·nvblox·cuMotion 패키지", 75, "대", "로봇 미들웨어·GPU 가속 인지·경로계획", "협동로봇 파지 대상 인지, AMR 장애물 지도(nvblox)", "EDGE-T", "무료"),
    ("제어 연동", "BRG", "로봇 제어 브리지", "로봇 SDK ↔ ROS 2 · 관절·TCP 명령 · 안전 I/O 상태 반영", 3, "식", "엣지 추론 결과를 로봇 제어기 명령으로 변환", "VLA가 낸 파지 궤적을 협동로봇 컨트롤러로 전달하고, 안전 PLC 정지 신호를 받으면 즉시 중단", "EDGE-T", "셀 BOM 미포함(추가)"),
    ("AI 추론", "VLA-R", "VLA·스킬 추론 런타임", "TensorRT·TensorRT-LLM · OpenVLA/π0.5 경량화·FP8/FP4 배포 · 모델 버전 고정", 1, "식", "카메라·관절·F/T 입력으로 다음 동작 생성", "A-3-5 R5가 커넥터 삽입 직전 손목 카메라(D405) 영상으로 위치를 보정해 삽입 궤적 생성", "EDGE-T", "자체 개발 (셀 BOM 'VLA'도 0원)"),
    ("AI 추론", "SAFE-AI", "엣지 안전·이상 감지 모델", "작업자 근접·파지 실패·F/T 이상 파형 감지 · 100ms 이내 판단", 1, "식", "로봇 단위 즉시 정지·재시도 판단", "가슴 카메라(D455)에 작업자가 들어오면 감속, F/T 파형이 정상 범위를 벗어나면 삽입 중단 후 HOLD 보고", "EDGE-T", "자체 개발"),
    ("데이터", "EPI", "에피소드 기록기", "카메라 3대 + 관절 100Hz + F/T 1kHz · PTP 시각동기 · LeRobot/RLDS 포맷", 1, "식", "로봇 1대 단위 멀티모달 에피소드 생성", "체결 1사이클(약 180초)을 order·episode ID로 묶어 저장", "EDGE-T", "자체 개발 (셀 BOM 'LOG'도 0원)"),
    ("데이터", "UPL", "업로드 에이전트", "영상 수집 노드로 청크 전송 · 단절 시 로컬 버퍼 · 체크섬 재전송", 1, "식", "엣지 기록분을 셀 영상 수집 노드로 전달", "AMR이 Wi-Fi 음영 구간을 지나는 동안 SSD에 쌓았다가 충전 중 일괄 전송", "EDGE-O", "자체 개발"),
    ("운영", "OTA", "컨테이너·OTA 에이전트", "K3s agent · 존 Gateway 관리와 연동 · 롤백", 75, "대", "추론 모델·기록기 버전 원격 배포", "새 VLA 모델을 A-3-5 협동로봇 10대에 동시 배포, 문제 시 이전 버전으로 롤백", "EDGE-T", "무료"),
    ("운영", "MONA", "엣지 모니터링 에이전트", "jtop · node-exporter · GPU·온도·전력 지표", 75, "대", "엣지 상태 감시", "엣지 GPU 온도·추론 지연이 임계값을 넘으면 존 모니터링에 알람", "EDGE-T", "무료"),
    ("보안", "ESEC", "엣지 보안 설정", "Secure Boot · OP-TEE · 디스크 암호화 · 장비 인증서", 1, "식", "엣지 위변조·데이터 유출 방지", "분실·교체된 엣지가 존 네트워크에 붙지 못하게 인증서로 차단", "EDGE-T", "셀 BOM 미포함(추가)"),
    ("NPU", "DXNN", "DXNN SDK", "DEEPX NPU 컴파일러·런타임", 10, "카피", "모델을 국산 NPU용으로 변환·실행", "작업자 근접 감지 모델을 DX-M1에서 돌려 Thor GPU 대비 지연·전력 비교", "EDGE-T", "무료"),
]

CELL_P = {
    "EDGE-T": ("MIC-743-AT (Jetson AGX Thor T5000, 128GB, 1TB)", "Advantech (대만) · NVIDIA", 900,
               "[추정] MIC-743 공개가 없음. 참고: Thor 개발자 키트 $3,499 [공개가·검색] + 산업용 섀시·광대역 전원·인증 → 견적 필요"),
    "EDGE-O": ("MIC-733-AO6A1 (Jetson AGX Orin 64GB)", "Advantech (대만) · NVIDIA", 680, "[공개가·검색] $4,779.99 ≈ 6,690"),
    "SSD": ("산업용 M.2 NVMe 2TB", "국산(삼성 등) 우선", 40, "[추정]"),
    "WLAN": ("산업용 Wi-Fi 6E 클라이언트 모듈", "Cisco·Moxa급", 50, "[추정]"),
    "5GM": ("AirLink XR60 (5G 산업용 라우터) + 5G 외장 안테나·케이블", "Sierra Wireless (Semtech, 미국·캐나다)", 236,
            "[공개가·검색] $1,473(판매가, MSRP $1,529) ≈ 2,060 + 안테나·케이블 약 300 [추정]. n79 지원은 판매처 사양으로 확인. 대안: Telit FN990A40 M.2 모듈 $335 ≈ 470(엣지 M.2 슬롯·안테나 필요). 국내 전파인증(KC)·이음5G 단말 등록 확인 필요"),
    "KIT": ("24VDC 컨버터·브래킷·M12 케이블 세트", "국내 조달", 30, "[추정]"),
    "NPU-M": ("DX-M1 M.2 모듈", "딥엑스 (한국)", 300, "[추정] 공개가 없음"),
    "JP": ("JetPack 7 / 6", "NVIDIA", 0, "무료"),
    "ROS": ("ROS 2 Jazzy · Isaac ROS", "Open Robotics · NVIDIA", 0, "무료"),
    "BRG": ("로봇 SDK–ROS 2 제어 브리지 개발", "자체 개발", 2000, "[추정] 로봇 기종군별(셀 공정군 3개) 개발"),
    "VLA-R": ("TensorRT·TensorRT-LLM + OpenVLA/π0.5 공개 모델", "NVIDIA·오픈소스 + 자체 개발", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). 미세조정·경량화·제어 연동은 연구 인력 수행"),
    "SAFE-AI": ("YOLO 계열 검출 모델 + 이상탐지 라이브러리", "오픈소스 + 자체 개발", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). 데이터 수집·라벨링·검증은 연구 인력 수행"),
    "EPI": ("LeRobot 기록 도구 확장", "Hugging Face(오픈소스) + 자체 개발", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). F/T·PTP·ID 태깅 확장"),
    "UPL": ("rclone·MinIO 클라이언트 설정", "오픈소스 + 자체 구성", 0, "연구 인력 자체 개발(오픈소스 기반, 인건비 처리). 기존 S3 전송 도구 설정 수준"),
    "OTA": ("K3s agent", "SUSE (오픈소스)", 0, "무료"),
    "MONA": ("jtop · node-exporter", "오픈소스", 0, "무료"),
    "ESEC": ("Jetson 보안 기능 설정·인증서 연동", "NVIDIA 기능 + 구축", 1000, "[추정] 구축"),
    "DXNN": ("DXNN SDK", "딥엑스 (한국)", 0, "무료(모듈 구매 시 제공)"),
}

CELL_SRC = {
    "EDGE-T": [("Thor 공식 사양", "https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-thor/"),
               ("개발자 키트 가격(검색)", "https://uk.rs-online.com/web/p/processor-development-tools/0606863"),
               ("MIC-743 출시 기사", "https://www.eenewseurope.com/en/advantech-brings-agentic-ai-to-jetson-thor-edge-platforms/")],
    "EDGE-O": [("Orin 공식 사양", "https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/"),
               ("MIC-733 사양", "https://buy.advantech.eu/Compact-Tower-Systems/AI-Jetson-Platforms-Edge-AI-Computer-Systems/model-MIC-733-AO6A1.htm"),
               ("가격(검색)", "https://www.cdw.com/product/advantech-mic-733-ao6a1-cff-jetson-agx-orin-cortex-a78ae-64-gb-ssd-64/8525915")],
    "SSD": [], "WLAN": [], "KIT": [],
    "5GM": [("XR60 가격(검색)", "https://www.shi.com/product/47602146/Sierra-Wireless-AirLink-XR60"),
            ("대안 FN990A40 사양·가격", "https://embeddedworks.net/product/wwan1931")],
    "NPU-M": [("DX-M1", "https://deepx.ai/products/dx-m1/")],
    "JP": [("JetPack", "https://developer.nvidia.com/embedded/jetpack")],
    "ROS": [("ROS 2 Jazzy", "https://docs.ros.org/en/jazzy/"), ("Isaac ROS", "https://nvidia-isaac-ros.github.io/")],
    "BRG": [], "SAFE-AI": [], "UPL": [], "ESEC": [],
    "VLA-R": [("TensorRT", "https://developer.nvidia.com/tensorrt")],
    "EPI": [("LeRobot", "https://github.com/huggingface/lerobot")],
    "OTA": [("K3s", "https://k3s.io/")],
    "MONA": [("Prometheus", "https://prometheus.io/")],
    "DXNN": [("딥엑스", "https://deepx.ai/")],
}
